export default VCARD;
declare class VCARD {
    static cardinalityOneProps: (typeof BeginProperty | typeof VersionProperty)[];
    static cardinalityOneOrMoreProps: typeof FNProperty;
    static cardinalityNoneOrOneProps: (typeof KindProperty | typeof NProperty | typeof BdayProperty | typeof AnniversaryProperty | typeof GenderProperty | typeof ProdidProperty | typeof RevProperty | typeof UIDProperty)[];
    static cardinalityNoLimitProps: (typeof SourceProperty | typeof XMLProperty | typeof NicknameProperty | typeof PhotoProperty | typeof AdrProperty | typeof TelProperty | typeof EmailProperty | typeof IMPPProperty | typeof LangProperty | typeof TzProperty | typeof GeoProperty | typeof TitleProperty | typeof RoleProperty | typeof LogoProperty | typeof OrgProperty | typeof MemberProperty | typeof RelatedProperty | typeof CategoriesProperty | typeof NoteProperty | typeof SoundProperty | typeof ClientpidmapProperty | typeof URLProperty | typeof KeyProperty | typeof FburlProperty | typeof CaladruriProperty | typeof CaluriProperty | typeof ExtendedProperty)[];
    constructor(props: any);
    repr(): string;
    value: string;
    props: any;
    #private;
}
import { BeginProperty } from "./properties.js";
import { VersionProperty } from "./properties.js";
import { FNProperty } from "./properties.js";
import { KindProperty } from "./properties.js";
import { NProperty } from "./properties.js";
import { BdayProperty } from "./properties.js";
import { AnniversaryProperty } from "./properties.js";
import { GenderProperty } from "./properties.js";
import { ProdidProperty } from "./properties.js";
import { RevProperty } from "./properties.js";
import { UIDProperty } from "./properties.js";
import { SourceProperty } from "./properties.js";
import { XMLProperty } from "./properties.js";
import { NicknameProperty } from "./properties.js";
import { PhotoProperty } from "./properties.js";
import { AdrProperty } from "./properties.js";
import { TelProperty } from "./properties.js";
import { EmailProperty } from "./properties.js";
import { IMPPProperty } from "./properties.js";
import { LangProperty } from "./properties.js";
import { TzProperty } from "./properties.js";
import { GeoProperty } from "./properties.js";
import { TitleProperty } from "./properties.js";
import { RoleProperty } from "./properties.js";
import { LogoProperty } from "./properties.js";
import { OrgProperty } from "./properties.js";
import { MemberProperty } from "./properties.js";
import { RelatedProperty } from "./properties.js";
import { CategoriesProperty } from "./properties.js";
import { NoteProperty } from "./properties.js";
import { SoundProperty } from "./properties.js";
import { ClientpidmapProperty } from "./properties.js";
import { URLProperty } from "./properties.js";
import { KeyProperty } from "./properties.js";
import { FburlProperty } from "./properties.js";
import { CaladruriProperty } from "./properties.js";
import { CaluriProperty } from "./properties.js";
import { ExtendedProperty } from "./properties.js";
